version: 2.1
orbs:
    docker: circleci/docker@0.5.20
jobs:
    build_test:
        working_directory: ~
        docker:
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run:
                  name: formatting-check
                  command: npx prettier -c **
            - run:
                  name: static-analysis
                  command: npm run lint
workflows:
    version: 2
    build_test_push:
        jobs:
            - build_test
            - docker/publish:
                  image: leonpatmore/spammer-v2-ui
                  tag: ${CIRCLE_SHA1}
                  update-description: true
